### ISSUE TITLE
Parameter priority

### ISSUE THREAD

**Issue by sfranky** [qtop/qtop#18]
Parameters accepted by qtop should be prioritized in the following order:
1. cmd line switches
2. environmental variables
3. config file

**Comment by fgeorgatos** [comment]
For the record, historic bash-based qtop has been doing exactly this, since ever!

Furthermore easybuild has adopted the same practice, as well:
https://easybuild.readthedocs.org/en/latest/Configuration.html?highlight=variables ### great read!
which implementation is visible somewhere around here in the codebase (kinda long read):
https://github.com/hpcugent/easybuild-framework/blob/master/easybuild/tools/options.py
